### ISSUE TITLE
Items should do stuff

### ISSUE THREAD

**Issue by Nauxitt** [Nauxitt/Extraprise#1]
Currently, the only implementation of items is "Items", an empty placeholder class.

**Comment by breitra** [comment]
should they have a basic use action? like every item has one specific "use"

**Comment by Nauxitt** [comment]
Something along those lines, yes.  A basic use system may not be comprehensive enough, though.  The difficult part seems to be making the item used in different kinds of actions.  For instance, we've got a gun.  Holding this should make `> shoot [target]` valid.  Any given object needs to have some kind of capability of interfacing with the command system.

However, I think something like `Item.on_use(agent, target)` could be useful.

**Comment by breitra** [comment]
Maybe if you look at an item you possess, it will tell you it's (agent) arg?

with no other context, naturally.

> Look gun
> 
> SHOOT

**Comment by Nauxitt** [comment]
I may have been overthinking there.  `agent` would be the player, assuming we wind up making the player into it's own class.  Currently, the player-related variables are stored in `World`, so an `agent` argument may be unnecessary.

**Comment by breitra** [comment]
Ah, I understand. So, in this case, a use would just have a target?

**Comment by Nauxitt** [comment]
Probably, yeah.  Whatever the case, an item should have some kind of access to the player's inventory.  If we wanted to program the gun to remove bullets from their inventory, for instance, this would be useful.

**Comment by Nauxitt** [comment]
Items have been added.  Each of them have a method called "command" which is given the parsed `Command` object which returns `True` on a successful command, stopping other items from getting that command.  One of their attributes is the `World` object, which gives them access to the player's inventory, location, and a method for getting the objects the user targets in commands such as `shoot captain`.  If I recall, you don't have to have `Item`s in your inventory to use them, but I haven't tested for sure.
